### PR TITLE
fix: should handle error

### LINKED ISSUE #560: The otomi validate values failure on kntaive service creation
**Describe the bug:**

**To Reproduce**

1. Go to otomi-console and create kntaive service for a team (see additional context)
2. Click on Deploy button
3. Observe that Drone pipeline fails on `tests` stage
See: https://drone.demo.aks.otomi.cloud/otomi/values/6/1/4

**Expected behavior:** 
Deployment of knative succeeds

**Cluster(s):**

- Cloud: azure
- Cluster: demo

**Additional context:**
```
2021-08-30T20:53:21.962Z otomi:validate-templates:warn WARN:  team-ns/templates/knative-services.yaml contains an invalid Service (my-nginx)
234	2021-08-30T20:53:21.962Z otomi:validate-templates:error Templating FAILED
235	2021-08-30T20:53:21.965Z otomi:global:error Error: ENOENT: no such file or directory, unlink '/tmp/otomi/test.yaml'
236	    at unlinkSync (node:fs:1708:3)
237	    at cleanup (file:///home/app/stack/dist/cmd/test.js:17:5)
238	    at file:///home/app/stack/dist/cmd/test.js:21:30
239	    at process.<anonymous> (file:///home/app/stack/dist/common/setup.js:121:9)
240	    at process.emit (node:events:406:35)
241	    at process.exit (node:internal/process/per_thread:184:15)
242	    at validateTemplates (file:///home/app/stack/dist/cmd/validate-templates.js:140:17)
243	    at processTicksAndRejections (node:internal/process/task_queues:96:5)
244	    at async test (file:///home/app/stack/dist/cmd/test.js:25:5)
245	    at async Object.handler (file:///home/app/stack/dist/cmd/test.js:53:9)
```
```
teamConfig:
    teams:
        gogo:
            services:
                -
                    name: my-nginx
                    port: 80
                    id: 680171cc-11e6-44b7-8fc0-6fc6fdd03007
                    ksvc:
                        image:
                            tag: stable
                            pullPolicy: IfNotPresent
                            repository: nginx
                        securityContext:
                            runAsUser: 1001
                            runAsGroup: 1001
                            runAsNonRoot: true
                        resources:
                            limits:
                                cpu: 50m
                                memory: 64Mi
                            requests:
                                cpu: 50m
                                memory: 64Mi
                        scaleToZero: false
                        containerPort: 80
                        autoCD: {}
                        annotations: {}
                        env: {}
                        files: {}
                        secretMounts: {}
                    ownHost: true
                    type: public
```

### PR DESCRIPTION
**Pull request by svatwork**
Closes #560. 

Should have handled exceptions with synchronous method (if file doesn't exist can't unlink).

### CODE REVIEW

**Review by Morriz — CHANGES_REQUESTED** [review]
Please use async method for cleanup, and don't "try"

**Comment by Dunky13** [comment]
> Please use async method for cleanup, and don't "try"

NO! Cleanup MUST be synchronous! Due to the `on exit` handler, that MUST be synchronous. So cleanup cannot - due to JS design - be asynchronous

File: src/cmd/test.ts [hunk 1]
```diff
@@ -14,11 +14,15 @@ import { validateValues } from './validate-values'
 
 const cmdName = getFilename(import.meta.url)
 const tmpFile = '/tmp/otomi/test.yaml'
-const debug: OtomiDebugger = terminal(cmdName)
+let debug: OtomiDebugger = terminal(cmdName)
 
 const cleanup = (argv: Arguments): void => {
+  debug = terminal(cmdName)
```
Comment (Dunky13) [inline src/cmd/test.ts:20]: Why do we need to set it here? It should be set up in the `setup` function. And only needs to be defined once.

**Comment by svatwork** [comment]
Also unlink (async) doesn't return a promise.

File: src/cmd/test.ts [hunk 2]
```diff
@@ -14,11 +14,15 @@ import { validateValues } from './validate-values'
...
   if (argv.skipCleanup) return
-  unlinkSync(tmpFile)
+  try {
+    unlinkSync(tmpFile)
+  }
+  catch (e) { debug.error(e) }
```
Comment (Dunky13) [inline src/cmd/test.ts:25]: Instead of a try catch:
```
if(existsSync(tmpFile)) unlinkSync(tmpFile)
```

Then no try/catch is necessary

**Review by Dunky13 — CHANGES_REQUESTED** [review]
Couple of comments

File: src/cmd/test.ts (hunk 1 above)
Comment (svatwork) [reply src/cmd/test.ts:20]: Ok sounds good.

File: src/cmd/test.ts (hunk 2 above)
Comment (svatwork) [reply src/cmd/test.ts:25]: Sort of, this is the implementation of existsSync:

```
fs.existsSync = function(path) {
  try {
    handleError((path = getPathFromURL(path)));
    nullCheck(path);
    binding.stat(pathModule._makeLong(path));
    return true;
  } catch (e) {
    return false;
  }
};
```

But I agree that this would be the preferable solution.

**Comment by svatwork** [comment]
BTW, I see prettier breaks the build, isn't it supposed to apply the fix when committing?

File: src/cmd/test.ts (hunk 2 above)
Comment (Dunky13) [reply src/cmd/test.ts]: I understand, but as @Morriz stated, prefer not to do try/catch. So if we know it exists, then we can safely remove it

File: src/cmd/test.ts [hunk 3]
```diff
@@ -14,14 +14,15 @@ import { validateValues } from './validate-values'
...
+let debug: OtomiDebugger = terminal(cmdName)
 
 const cleanup = (argv: Arguments): void => {
   if (argv.skipCleanup) return
-  unlinkSync(tmpFile)
+  if(existsSync(tmpFile)) unlinkSync(tmpFile)
 }
 
 const setup = (argv: Arguments): void => {
+  debug = terminal(cmdName)
```
Comment (Morriz) [inline src/cmd/test.ts:25]: this is already done on line 17, so you can remove this line

File: src/cmd/test.ts (hunk 2 above)
Comment (svatwork) [reply src/cmd/test.ts]: Apparently you do not? Your suggestion of existsSync is basically a wrapper of try catch right?

**Review by Morriz — CHANGES_REQUESTED** [review]

File: src/cmd/test.ts (hunk 3 above)
Comment (svatwork) [reply src/cmd/test.ts:25]: Brainfart sorry

**Review by Dunky13 — APPROVED** [review]
lgtm

**Comment by Dunky13** [comment]
> BTW, I see prettier breaks the build, isn't it supposed to apply the fix when committing? Or pushing? If pushing, can we tone that script down a bit because it takes so long.

Prettier should run on any `git push` (unless you run with `--no-verify` but then CI will break) If it finds anything it doesn't like it will exit and not push. You should fix prettier's complaints, commit and try to push again.
If you want push to succeed on the first try, then run `npm run lint` or (`npm run lint:ts` if you changed only `src/**` files) and see if there are complaints.

We shouldn't tone it down, and I dislike the use of `--no-verify` personally because it just moves the check from local machine to GH Action. The pre-push it there for a reason: To have CI fail on errors that are not lint related, and have the code style across multiple commits the same.

Prettier is able to fix some issues, but not commit them for you, so push would fail anyway.

**Comment by svatwork** [comment]
I don't agree, I'm not going to wait for that script every time I want to commit

**Comment by Dunky13** [comment]
> I don't agree, I'm not going to wait for that script every time I want to commit

Correct, that's why it's a `pre-push` not a `pre-commit`

**Review by Morriz — APPROVED** [review]
