### PR TITLE
fix(alerting): fixes issues in #797

### LINKED ISSUE #797: alerting setup issues
**Describe the bug:** (a clear and concise description of what the bug is)
Tried setting up alertmanager to send some alerts to opsgenie together with @staticvoid255. However, we ran into the following issues:

1) Communication between Alertmanager and Prometheus within a team-namespace is not possible if Otomi ingress networkpolicies are deployed. We deployed these netpols as temporary fix:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: temp-fix-prometheus-to-alertmanager
  namespace: team-X
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: team-X
      podSelector:
        matchLabels:
          prometheus: X-po-prometheus 
  podSelector:
    matchLabels:
      alertmanager: X-po-alertmanager
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: temp-fix-alertmanager-to-prometheus
  namespace: team-X
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: team-X
      podSelector:
        matchLabels:
          alertmanager: X-po-alertmanager
  podSelector:
    matchLabels:
      prometheus: X-po-prometheus 
  policyTypes:
  - Ingress
 ```

2) Communication between Kube-state-metrics and Prometheus within a team-namespace is not possible if Otomi ingress networkpolicies are deployed. (deployed a similar networkpolicy to the one above)

3) a team's Prometheus should contain a `probeNamespaceSelector` like below, so it wont allow teams to check all namespaces.
```yaml
probeNamespaceSelector
    matchLabels:                                                                                                                                                                                                        
        name: team-X 
```
4) Teams are able to view alerts from other namespaces. This can be fixed by setting `defaultRules.appNamespacesTarget` to the team's namespace (in prometheus-operator values).

5) ~~We noticed that when setting Opsgenie api-key and url in Otomi UI, these values were not stored in gitea and `selfService` values are duplicated now, see here the redacted content of the `values/env/teams.yaml`:~~
**edit:** Will move this issue to the right repo, not otomi-core.
```yaml
    teamX:
        oidc:
            groupMapping: xxx
        alerts:
            receivers:
                - opsgenie
        resourceQuota:
            pods: '100'
        networkPolicy:
            egressPublic: false
            ingressPrivate: true
        selfService:
            service:                                 
                - ingress
                - networkPolicy
            team:
                - alerts
            Service:                               
                - ingress
            Team:
                - alerts
            apps: []
        id: teamX
```

6) Alertmanager is not updated with new opsgenie configuration. Its config-reloader container does not seem to update `alertmanager-teamx-po-alertmanager-generated` secret while the `alertmanager-teamx-po-alertmanager` secret is updated. ~~(not sure yet why).~~
**edit:** found the issue, opsgenie_configs[].tags is expecting a string (csv), not an array, will create a PR with fixes. 


Otomi core version: v0.16.3
Otomi api version: 0.5.5
Otomi console version: 0.5.9
K8S version: 1.21.2

### PR DESCRIPTION
**Pull request by bartusz01**
fix #797

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [x] Helm releases are meeting otomi's baseline security policies, if applicable.
- [x] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

### CODE REVIEW

**Review by j-zimnowoda — APPROVED** [review]
Well done :)

File: helmfile.d/helmfile-60.teams.yaml [hunk 1]
```diff
@@ -72,6 +72,8 @@ releases:
           alertmanagerSpec:
             externalUrl: https://{{ $appsDomain }}/alertmanager
           config: {{- tpl (readFile "../helmfile.d/snippets/alertmanager.gotmpl") (dict "instance" $team "root" $v "slackTpl" $slackTpl "opsgenieTpl" $opsgenieTpl) | nindent 12 }}
+        defaultRules:
```
Comment (j-zimnowoda) [inline helmfile.d/helmfile-60.teams.yaml:75]: There are two `defaultRules` properties now. I believe they should be merged.

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]

**Review by j-zimnowoda — APPROVED** [review]
