### PR TITLE
fix: performance issues yq #261

### LINKED ISSUE #261: performance issues yq
The 5 bats tests are not performing well. They should run under 5 seconds imo. Can this be optimized?

### PR DESCRIPTION
**Pull request by Dunky13**
Using jq for faster recursive key deletion.

fix #261

### CODE REVIEW

File: bin/bootstrap.sh [hunk 1]
```diff
@@ -14,11 +14,12 @@ has_otomi='false'
 [ -f $ENV_DIR/bin/otomi ] && has_otomi='true'
 
 function generate_loose_schema() {
-  local targetPath="$ENV_DIR/.vscode/values-schema.yaml"
-  local sourcePath="$PWD/values-schema.yaml"
-  yq d $sourcePath '**.required.' | yq d - 'properties.toolsVersion' | yq d - 'properties.cluster' >$targetPath
+  local targetPath="${ENV_DIR}/.vscode/values-schema.yaml"
+  local sourcePath="${PWD}/values-schema.yaml"
```
Comment (Morriz) [inline bin/bootstrap.sh:18]: please no unneeded chars

**Review by Morriz — CHANGES_REQUESTED** [review]

**Review by svatwork — COMMENTED** [review]
Awesome that the performance is improved now. It might be a "nice to have" and not a "must have" for this change, but since the `generate_loose_schema` function is a module in the `bin/bootstrap.sh` script (ie. it can be tested by bats by importing the function), you could add a test to `bin/tests` with an example `sourcePath` and `targetPath` testing this function.

File: bin/bootstrap.sh (hunk 1 above)
Comment (Dunky13) [reply bin/bootstrap.sh:18]: Same reason as https://github.com/redkubes/otomi-core/pull/271#discussion_r562634102
Just following the style guide, but I'll remove.

File: bin/tests/bootstrap.bats [hunk 2]
```diff
@@ -55,4 +55,27 @@ teardown () {
...
+    [ "$result" -ne 0 ]
+    result=$(yq r "$PWD/values-schema.yaml" 'properties.cluster' | wc -l)
+    [ "$result" -ne 0 ]
+
+    result=$(yq r "$ENV_DIR/.vscode/values-schema.yaml" '**.required.' | wc -l)
+    [ "$result" -eq 0 ]
+    result=$(yq r "$ENV_DIR/.vscode/values-schema.yaml" 'properties.toolsVersion' | wc -l)
+    [ "$result" -eq 0 ]
+    result=$(yq r "$ENV_DIR/.vscode/values-schema.yaml" 'properties.cluster' | wc -l)
+    [ "$result" -eq 0 ]
```
Comment (Morriz) [inline bin/tests/bootstrap.bats:79]: Why are we suddenly addings tests that only test the workings of yq here? Can we discuss these things first? This is undesirable

**Review by Morriz — CHANGES_REQUESTED** [review]
please ditch the "tests" that were just added

File: bin/tests/bootstrap.bats (hunk 2 above)
Comment (Dunky13) [reply bin/tests/bootstrap.bats:79]: @Morriz was discussed as desirable during standup. 
It is not testing the workings of yq, but verifying that the original yaml contains these keys, and the new yaml does not contain these keys.
So it verifies that the (now speed optimized) removes these fields correctly.

Comment (Morriz) [reply bin/tests/bootstrap.bats:79]: It is testing nothing of our code. It is merely testing if yq does what you ask it to do. Call me if you want further clarification.

Comment (svatwork) [reply bin/tests/bootstrap.bats:79]: @Morriz we could've discussed this during stand-up. It can't be that you have to micro-manage every piece of code, it's like you don't trust anyone.

I'm just going to lay out how I experienced it. First you create an issue that the performance of the bats testing is not good. That's true, it takes about 30 seconds. Of course there's yq to blame, but it's not nice to reproach me about code you added. Then when I mention the performance gain of piping to jq, you don't believe me.

Now this test will actually test if the behaviour is the same of pre-jq and post-jq. It's about 6 lines of code and to me it seems like this would improve coverage because the logic is actually in the function `generate_loose_schema`. If someone adds a different piece of logic, say, we don't need to remove the required keys anymore (I don't actually understand why those need to be removed in the first place, since it's valid json schema), then this test will complain and that makes it easier to debug. 

Of course, if there is anything wrong about my reasoning then I'm open to learn from you, as always.

File: charts/team-ns/values.yaml [hunk 3]
```diff
@@ -1,4 +1,4 @@
-toolsVersion: 1.3.5
+toolsVersion: v1.4.11
```
Comment (Dunky13) [inline charts/team-ns/values.yaml:1]: @Morriz why did I have to put `v1.4.11` here and not `1.4.11` as the old version was just `1.3.5`

**Review by Dunky13 — COMMENTED** [review]
@Morriz why use the `v` for version?

File: values/otomi-api/otomi-api.gotmpl [hunk 4]
```diff
@@ -51,8 +51,8 @@ tools:
   enabled: {{ $v.sops.enabled }}
   {{- if $v.sops.enabled }}
   image:
-    pullPolicy: {{ $o | get "tools.image.pullPolicy" "IfNotPresent" }}
-    tag: {{ $o | get "tools.image.tag" "latest" }}
```
Comment (svatwork) [inline values/otomi-api/otomi-api.gotmpl:55]: I'm curious, why should we hardcode this? I can imagine that we will bump tools often? @Morriz

Comment (svatwork) [reply values/otomi-api/otomi-api.gotmpl:55]: Also, is it part of the task?

**Comment by Dunky13** [comment]
@Morriz could it be that since you had me remove the "toolsVersion" definition in `value-schema.yaml` that since there is still a "toolsVersion" key/value in `core.yaml` and `chars/team-ns/values.yaml` that the `validate-values` complains?

I don't know how to proceed to fix this and have CI stop complaining. And it also seems out-of-scope for this issue/task. Should we revert & recreate in separate issue?

**Comment by Morriz** [comment]
It is about relationship with a version the context expects. Indeed it can happen that all contexts demand an upgrade (like for kubectl minor bumps), but a one for all approach could introduce a breaking change that breaks a context demanding the old image.

Maybe I see this wrong but now we have control over that. If we can avoid such breakages and instead use one for all that would be great. But we have to rely on code for that, not human process.

I don’t see that go away easily.

**Comment by svatwork** [comment]
> It is about relationship with a version the context expects. Indeed it can happen that all contexts demand an upgrade (like for kubectl minor bumps), but a one for all approach could introduce a breaking change that breaks a context demanding the old image. Maybe I see this wrong but now we have control over that. If we can avoid such breakages and instead use one for all that would be great. But we have to rely on code for that, not human process. I don’t see that go away easily.

I can agree with this proposition, and I definitely see the benefits. Of course, I could also argue that detecting breaking changes should be part of our CI. 

Besides that, I don't see why this should be part of this task, it seems like something we should discuss. I hope we can enter a discourse on this topic.

**Comment by Morriz** [comment]
@Dunky13 can you resolve these conflicts? You can ask help from me tomorrow if needed...

**Comment by Dunky13** [comment]
> @Dunky13 can you resolve these conflicts? You can ask help from me tomorrow if needed...

I would love to, but have not been able to resolve this (yet). Help is necessary

**Comment by svatwork** [comment]
@Morriz but can we please stay within the issue of improving yq performance?

**Comment by j-zimnowoda** [comment]
> @Morriz could it be that since you had me remove the "toolsVersion" definition in `value-schema.yaml` that since there is still a "toolsVersion" key/value in `core.yaml` and `chars/team-ns/values.yaml` that the `validate-values` complains?
> 
> I don't know how to proceed to fix this and have CI stop complaining. And it also seems out-of-scope for this issue/task. Should we revert & recreate in separate issue?

@Morriz, adding `toolsVersion` value in `core.yaml` file and not defining this property in `values-schema.yaml`  causes validation error. Before requesting changes and enforcing them, please think about how does it work. Otherwise you are providing very confusing requirements that people cannot meet.

**Comment by Morriz** [comment]
Then that caught by our update. Great! So it should be removed from the values.

File: values/otomi-api/otomi-api.gotmpl (hunk 4 above)
Comment (Morriz) [reply values/otomi-api/otomi-api.gotmpl:55]: resolved in another conversation ;)

File: charts/team-ns/values.yaml (hunk 3 above)
Comment (Morriz) [reply charts/team-ns/values.yaml:1]: we are using `v*` tags now?

Comment (Morriz) [reply charts/team-ns/values.yaml:1]: we have to remove this line as we don't use the global `toolsVersion` in any code now

File: core.yaml [hunk 5]
```diff
@@ -1,3 +1,4 @@
+# NOTE: This file is merged with other values in ./helmfile.d/snippets/env.gotmpl
 toolsVersion: 1.4.9
```
Comment (Morriz) [inline core.yaml:2]: this line has to go

File: docs/BATS.md [hunk 6]
```diff
@@ -4,11 +4,11 @@ This document is relevant starting from [v0.11.52](https://github.com/redkubes/o
 
 ## Where can I find BATS?
 
-The otomi/tools:1.4.10 includes the [bats framework](https://github.com/bats-core/bats-core), including libraries [bats-assert](https://github.com/ztombol/bats-assert), [bats-file](https://github.com/ztombol/bats-support) and [bats-support](https://github.com/ztombol/bats-support). These links include relevant documentation, such as syntax, which won't be discussed on this page.
+The otomi/tools:1.4.10 or newer includes the [bats framework](https://github.com/bats-core/bats-core), including libraries [bats-assert](https://github.com/ztombol/bats-assert), [bats-file](https://github.com/ztombol/bats-support) and [bats-support](https://github.com/ztombol/bats-support). These links include relevant documentation, such as syntax, which won't be discussed on this page.
 
 Example of calling the binary:
 
-`docker run --rm otomi/tools:1.4.10 bats bin/tests`
+`docker build --target test .`
```
Comment (Morriz) [inline docs/BATS.md:11]: please don't change this...it will also run the other tests, including the one in the parent image

File: values-schema.yaml [hunk 7]
```diff
@@ -1371,7 +1371,9 @@ properties:
           '^[a-z-]+$':
             $ref: '#/definitions/team'
   toolsVersion:
```
Comment (Morriz) [inline values-schema.yaml:1373]: remove this

**Review by Morriz — CHANGES_REQUESTED** [review]
small potatoes left

File: core.yaml (hunk 5 above)
Comment (Dunky13) [reply core.yaml:2]: That line was suggested by @j-zimnowoda

File: docs/BATS.md (hunk 6 above)
Comment (Dunky13) [reply docs/BATS.md:11]: The `old` line doesn't work
```
marc@Marcs-MBP otomi-core % docker run --rm otomi/tools:1.4.10 bats bin/tests
/usr/local/libexec/bats-core/bats: line 59: cd: bin: No such file or directory
```

File: values-schema.yaml (hunk 7 above)
Comment (Dunky13) [reply values-schema.yaml:1373]: If I remove that the CI will fail. @j-zimnowoda can explain better why.

File: core.yaml (hunk 5 above)
Comment (j-zimnowoda) [reply core.yaml:2]: yes, I suggested it because it is not obvious that `core.yaml` is part of merged values.
Our colleagues spend a significant time on finding out the root cause of the validation issue, because they did not know about that. I think it is worth to have this command if it can save someone's time in the future.

File: values-schema.yaml (hunk 7 above)
Comment (j-zimnowoda) [reply values-schema.yaml:1373]: @Morriz if you want `toolsVersion` to be part of values, then it has to be defined in values-schema.yaml

File: docs/BATS.md (hunk 6 above)
Comment (j-zimnowoda) [reply docs/BATS.md:11]: The otomi/tools:1.4.10 does not have bats binary
Moreover otomi/tools does not contain bin/test directory. It is included in otomi-core,
Should be:
```
docker run --rm otomi/core:latest bats bin/tests/bootstrap.bats 
```

File: charts/team-ns/values.yaml (hunk 3 above)
Comment (j-zimnowoda) [reply charts/team-ns/values.yaml:1]: True, this is kind of dead configuration, not used in `team-ns` chart

File: docs/BATS.md (hunk 6 above)
Comment (Dunky13) [reply docs/BATS.md:11]: `otomi/tools` has the bats binary, but not the tests nor the code that should be tested. So we do need `otomi/core` to run the bats test

File: values-schema.yaml (hunk 7 above)
Comment (Morriz) [reply values-schema.yaml:1373]: nope, I said the opposite: remove it everywhere

**Review by Morriz — APPROVED** [review]
YAY!
